language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.8-dev"

install:
  - pip install codecov coverage pytest==3.3.2
  - python setup.py install

script:
  - coverage run --m tests
  - coverage run -a --m tests
  # exclude bootstrap for ast transformations cannot be detected by coverage, causing incorrect report.
  - coverage report

after_success:
  - codecov
